[tool.poetry]
name = "aiotone"
version = "19.9.0"
description = "Beep beep."
authors = ["Łukasz Langa <lukasz@langa.pl>"]

[tool.poetry.dependencies]
python = "^3.7"
python-rtmidi = "^1.3"
uvloop = "^0.14.0"
click = "^7.0"
black = {version = "^19.10-beta.0", allow-prereleases = true}
[tool.poetry.dev-dependencies]
pytest = "^3.0"
mypy = "^0.750"
flake8 = "^3.7"
flake8-bugbear = "^19.8"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
